[package]
name = "async_client"
version = "0.1.0"
edition = "2021"

[dependencies]
EasyAlgolia = { version = "1.0.1", path = "../.." }
dotenv = "0.15.0"
dotenvy = "0.15.7"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["rt"] }
