name: EasyAlgolia

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: fmt code
    - name: codefmt
      run: cargo fmt
    - name: test code
      run: cargo test 
